language: ruby
rvm: 2.2.0
sudo: required

before_install:
- openssl aes-256-cbc -K $encrypted_cf9135e7887d_key -iv $encrypted_cf9135e7887d_iv -in GAE-test-6abbbeac2135.json.enc -out GAE-test-6abbbeac2135.json -d

install:
  -echo "Nothing to Install"

script:
- echo "No Script to run"

# [START travis_deploy]
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: GAE-test-6abbbeac2135.json.enc
  project: GAE-test-158421
  default: true
# [END travis_deploy]
